### ISSUE TITLE
Sensor/switch support

### ISSUE THREAD

**Issue by titilambert** [balloob/aiohue#1]
Hello !
Will you accept sensor/switch support Pull request ?
With that we could catch "kind of events" from the bridge and do something in home assistant.

**Comment by balloob** [comment]
I want aiohue to remain a 1 on 1 mapping on the Philips Hue API. So if they have a Rest endpoint to query sensor / switch info, yes I would be open for that.

**Comment by christian1986** [comment]
Any progress at all on getting sensors in?

Astonishing how long time gone by since the api was updated, still nothing here😢

**Comment by balloob** [comment]
A PR is welcome @christian1986

**Comment by Moumoustache** [comment]
hey there,

i have a weird behaviour with new zigbee 3.0 lamps in my hue bridge. It seems for those new bulbs only, everytime i request a state change from home assistant it fades incorrectly...the weirdest thing is, when i made a restful switch based on the hue api it works perfectly

```
switch:
  - platform: rest
    method: put
    resource: http://192.168.0.10/api/rEE8fqPYSS9w4uRivOMpbyUtIkKP8BWtnD65HDrL/lights/10/state
    body_on: '{"on": true}'
    body_off: '{"on": false}'
```

I was suspecting a change in hue api impacting zigbee 3.0 lights only...any clue ?
